___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

![Image_Assignment](https://i.ibb.co/cY9HhF7/bnote-assignment.gif)

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:200%; text-align:center; border-radius:10px 10px;">Assignment 01 (NumPy & Pandas Basics)</p>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [NUMPY SECTION](#0)
* [PANDAS SECTION](#1)


**In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!**

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Section</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### 1. Import NumPy Library.

In [173]:
import numpy as np



### 2. Create an array from my_list = [5, 10, 15, 20, 25]

In [3]:
my_list = np.array([5, 10, 15, 20, 25])
my_list



array([ 5, 10, 15, 20, 25])

### 3. Generate an array of 5x5 with zeros. 

In [4]:
my_zeros = np.zeros((5,5))
my_zeros



array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 4. Generate an array of 4x4 with ones and assign data type as int.

In [5]:
arr_ones = np.ones((4,4), dtype=int)
arr_ones


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### 5. Make all the values of the array above with the value of 7.

In [6]:
arr2= np.array(arr_ones)*7
arr2



array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 6. Create the previous array above by full() method.

In [7]:
arr3 = np.full((4,4), [7])
arr3



array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 7. Create an array of even integers from 2 to 16 (inclusive). 

In [8]:
even = np.arange(2,17,2)
even



array([ 2,  4,  6,  8, 10, 12, 14, 16])

### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive).

In [9]:
arr1 = np.arange(25).reshape(5,5)
arr1
                             



array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [10]:
arr4 = np.random.randint(25, size=[5,5])
arr4

array([[16, 12,  8, 19,  3],
       [21,  7,  5,  3, 12],
       [19,  1, 12,  1,  9],
       [ 5, 13, 24,  4, 19],
       [ 6, 10,  9,  3, 24]])

### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace method.

In [11]:
linspace_m = np.linspace(0,24,25).reshape(5,5)
linspace_m



array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

### 10. Create randomly 5 numbers with numpy.

In [12]:
from numpy import random

x = random.randint((100), size = 5)

print(x)



[49 49 65 63 51]


In [13]:
from numpy import random

x = random.randn(5)

print(x)

[-1.39307665 -1.60281916  0.18043206 -1.96258813  1.08632857]


### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution.

In [14]:
my_randn = np.random.randn(25)
my_randn



array([-0.40303953, -1.57206622,  0.02351114,  2.06567941,  1.06440726,
        0.83034891, -0.59963913, -1.22075039,  0.29353442,  0.31706275,
        0.59519843, -1.89742471, -0.69162632, -0.2512453 , -0.55580724,
       -1.07527265,  1.4445248 , -0.38317202,  1.34812673,  0.27619368,
        0.46812915, -0.8994869 , -0.94391167,  0.63419029,  0.77907063])

### 12. Create a 3*4 array of random int numbers between 20 and 50.

In [15]:
my_list = np.random.randint(20,50, size=(3,4))
my_list



array([[35, 49, 43, 36],
       [33, 46, 36, 27],
       [44, 34, 47, 46]])

### 13. Create an array named "ranarr"consisting of randomly 48 numbers and reshape this array with the shape of 6x8 in different ways.

In [16]:
ranarr = np.random.rand(48).reshape(6,8)
ranarr



array([[0.78633795, 0.98561435, 0.67830082, 0.74298705, 0.90697373,
        0.91642877, 0.42154248, 0.65032052],
       [0.85340973, 0.39761352, 0.20293183, 0.47605219, 0.90698313,
        0.69057404, 0.16392991, 0.11146944],
       [0.82113893, 0.31935009, 0.03280511, 0.31506162, 0.05982129,
        0.54542518, 0.81293468, 0.18403855],
       [0.07126353, 0.03838858, 0.5644554 , 0.59565502, 0.87054303,
        0.76408088, 0.91568345, 0.07268353],
       [0.72211988, 0.94228906, 0.65624321, 0.3362399 , 0.53666867,
        0.03288626, 0.81460066, 0.85652909],
       [0.34583915, 0.9949184 , 0.22967153, 0.87477499, 0.95744382,
        0.25232458, 0.42094233, 0.59054984]])

In [18]:
rng = np.random.default_rng()
rng.choice((5,5), size=(6,8))



array([[5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5]])

In [84]:
ranarr2 = np.random.default_rng()
rng.choice(np.arange(100), size=(6,8))

array([[65, 55, 31, 49, 77, 19,  3, 12],
       [82, 20, 62, 47, 28, 26, 80, 28],
       [27, 96, 73, 18, 96, 41, 11, 42],
       [23, 13, 55, 27, 69,  8, 74, 66],
       [55, 34, 66, 45, 93, 26, 48, 53],
       [26, 42, 38, 43, 43, 78, 78, 12]])

In [19]:
ranarr3 = np.random.default_rng()
rng.choice(np.random.randint(1000), size=(6,8))



array([[249, 174, 413,  58,  34,  29, 216, 177],
       [546, 433, 624, 377,  71, 161,  18, 123],
       [301, 328, 418, 372,  64, 132, 206, 506],
       [506, 182, 116, 280, 491, 273, 224, 321],
       [381, 620, 485, 500, 249, 366, 321, 442],
       [667, 590, 372,  30, 426, 231, 436, 200]])

## Numpy Indexing and Selection

### Create an array named "mat" in accordence with the desired output below.

In [84]:
mat = np.arange(1,17).reshape(4,4)
mat


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### 14. Using the array above, write a code that reproduces the desired output shown below.<br>

In [61]:
mat[1:3, 1:3]


array([[ 6,  7],
       [10, 11]])

### 15. Get the 1st column (index number 0) of the array above.

In [62]:
mat[:, 0]


array([ 1,  5,  9, 13])

### 17.Assign 77 to every cell in 3rd column.

### 16. Get the values in 2nd row (index number 1) for every 2 step.

In [63]:
np.concatenate([mat[1:2, 0 ], mat[1:2, 2]])


array([5, 7])

In [79]:
mat[1,[0,2]]

array([5, 7])

In [89]:
mat[:, 2:3] = 77
mat




array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

### 18. (a) Take 2nd row (index number 1) and 1st column (index number 0) , (b) 4th row (index number 3) and 3rd column (index number 2) .

In [100]:
np.concatenate([mat[1:2, 0 ], mat[3:4, 2]])

array([ 5, 77])

### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [105]:
np.concatenate([mat[1:2, 0 ], mat[1:2, 2], mat[3:4, 0 ], mat[3:4, 2]]).reshape(2,2)


array([[ 5, 77],
       [13, 77]])

## NumPy Operations

### 20. Get the sum of values smaller than 10 and values bigger than 12 in "mat".

In [106]:
# LET US REMEMBER OUR ARRAY OF "mat
mat



array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [108]:
# LET US FIND THE VALUES SMALLER THAN 10 IN " MAT
mat1 = mat < 10
mat[mat1]



array([1, 2, 4, 5, 6, 8, 9])

In [110]:
# LET US FIND THE VALUES BIGGER THAN 12 IN "mat" 

mat2 = mat > 12
mat[mat2]



array([77, 77, 77, 13, 14, 77, 16])

In [114]:
# LET US SUM THE VALUES SMALLER THAN 10 AND BIGGER THAN 12 IN "mat" 

mat3 = (mat < 10) | (mat > 12)
mat[mat3]



array([ 1,  2, 77,  4,  5,  6, 77,  8,  9, 77, 13, 14, 77, 16])

### 21. Get the standard deviation (std) of the result above.

In [116]:
np.std(mat[mat3])



31.533914363777313

### 22. Get the sum of the 2nd column in the original "mat".

In [117]:
# LET US REMEMBER OUR ARRAY OF "mat" 

mat



array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [120]:
# LET OBTAIN THE ORIGINAL ARRAY OF "mat" 

np.sum(mat[:, 1:2])



32

In [ ]:
# YOUR CODE IS HERE 



### 23. Get the median, mean and std of 3rd column in "mat".

In [121]:
# LET US REMEMBER OUR ARRAY OF "mat" 
mat = np.arange(1,17).reshape(4,4)
mat



array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [124]:
# LET US ASSIGN THE COLUMN WE ARE INTERESTED IN TO A VARIABLE 
arr = mat[:, 2:3]
arr




array([[ 3],
       [ 7],
       [11],
       [15]])

In [125]:
# WHAT IF WE ARE INTERESTED IN THE 3RD ROW? 

arr1 = mat[2:3, :]
arr1


array([[ 9, 10, 11, 12]])

In [129]:
# LET US GET MEDIAN VALUE 

print(np.median(arr))
print(np.median(arr1))



9.0
10.5


In [131]:
# LET US GET MEAN VALUE 

print(np.mean(arr))
print(np.mean(arr1))



9.0
10.5


In [135]:
# LET US GET STANDART DEVIATION (std) VALUE 

print(np.std(arr))
print(np.std(arr1))



4.47213595499958
1.118033988749895


## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Pandas Section</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### Import Pandas Library

In [174]:
import pandas as pd

### Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements.*

In [142]:
# LET US READ Salaries.csv 

from google.colab import files
uploaded = files.upload()




Saving Salaries.csv to Salaries.csv


In [143]:
import io
df2 = pd.read_csv(io.BytesIO(uploaded['Salaries.csv']))


In [175]:
df2

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided        NaN   
148651                                    Not provided        NaN   
148652                                    Not provided        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653         0.00    -618.13       0.0    -618.13           -618.13  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
148649    NaN  San Francisco     NaN  
148650    NaN  San Francisco     NaN  
148651    NaN  San Francisco     NaN  
148652    NaN  San Francisco     NaN  
148653    NaN  San Francisco     NaN  

[148654 rows x 13 columns]

In [148]:
# LET US LOOK AT THE FIRST 5 ROWS 

df2[0:5]



Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

Desired Output:

![image.png](https://i.ibb.co/6BTmGX8/assignment1a.png)

In [176]:
# LET US GET A SAMPLE 

df = df2.sample()
df


Id    EmployeeName         JobTitle   BasePay  OvertimePay  \
132546  132547  Rafael Teuntor  General Laborer  61241.24          0.0   

        OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  Notes  \
132546   1145.39  27368.89  62386.63          89755.52  2014    NaN   

               Agency  Status  
132546  San Francisco     NaN

Desired Output (WATCH OUT! Your output may NOT be the same as the one):

![image.png](https://i.ibb.co/mcsCxxC/assignment1b.png)

In [171]:
# YOUR CODE IS HERE 
df2.info()



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [170]:
# LET US GET SOME DESCRIPTIVE MEASUREMENTS  

df2.describe()



Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448840    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

In [178]:
import seaborn as sns

Desired Output:

![image.png](https://i.ibb.co/ftMP67H/assignmnet1c.png)

### How many different year values are there?

In [181]:
df2



Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided        NaN   
148651                                    Not provided        NaN   
148652                                    Not provided        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653         0.00    -618.13       0.0    -618.13           -618.13  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
148649    NaN  San Francisco     NaN  
148650    NaN  San Francisco     NaN  
148651    NaN  San Francisco     NaN  
148652    NaN  San Francisco     NaN  
148653    NaN  San Francisco     NaN  

[148654 rows x 13 columns]

In [182]:
df2.Year.value_counts()

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

In [183]:
# LET US FIND THE NUMBER OF UNIQUE VALUES IN THE COLUMN OF "Year"
df2.Year.nunique()



4

In [184]:
# LET US FIND THE UNIQUE VALUES IN THE COLUMN OF "Year"

df2.Year.unique()



array([2011, 2012, 2013, 2014])

### Print out max and avg values in the column of "Totalpay".

In [185]:
# LET US FIND THE MAXIMUM TOTALPAY

df2.TotalPay.max()



567595.43

In [186]:
# LET US FIND THE AVERAGE TOTALPAY

df2.TotalPay.mean()



74768.32197169267

### How many records in the TotalPay column are there bigger than avg TotalPay?

In [189]:
df2.loc[(df2.TotalPay > df2.TotalPay.mean())]



Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
135701  135702    Christina S Jee   
135778  135779  Mary Ann T Abille   
135847  135848   Emilda E Reinosa   
135853  135854      David G Evans   
136063  136064         Nicole Joe   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
135701                              Nurse Practitioner   70635.61   
135778                                   Special Nurse   60889.34   
135847                                   Special Nurse   76305.74   
135853                                   Special Nurse   71178.15   
136063                                   Special Nurse   61276.59   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
135701         0.00    6550.41    771.88   77186.02          77957.90  2014   
135778      6815.67    9041.21    767.47   76746.22          77513.69  2014   
135847         0.00       0.00    763.08   76305.74          77068.82  2014   
135853      2748.15    2354.40    762.81   76280.70          77043.51  2014   
136063      8538.44    5078.67    748.95   74893.70          75642.65  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
135701    NaN  San Francisco     NaN  
135778    NaN  San Francisco     NaN  
135847    NaN  San Francisco     NaN  
135853    NaN  San Francisco     NaN  
136063    NaN  San Francisco     NaN  

[69489 rows x 13 columns]

Desired Output:

![image.png](https://i.ibb.co/nj84FbZ/assignment1d.png)

In [194]:
df2.loc[df2.value_counts((df2.TotalPay > df2.TotalPay.mean()))]



Id       EmployeeName                       JobTitle    BasePay  \
79165  79166  Rafael P Restauro  Institutional Police Sergeant  116599.00   
69489  69490     Rebekah Kaplan                  Nurse Midwife    7727.65   

       OvertimePay  OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
79165     10343.58   4790.05  35139.26  131732.63         166871.89  2013   
69489         0.00      0.00    614.95    7727.65           8342.60  2012   

       Notes         Agency  Status  
79165    NaN  San Francisco     NaN  
69489    NaN  San Francisco     NaN

### How much does ALBERT PARDINI make money (including benefits)?

In [197]:
df2.loc[df2.TotalPayBenefits()]



TypeError: ignored

### Who is the lowest paid person?

In [ ]:
# YOUR CODE IS HERE 



### What are the unique Jobs in dataset?

In [ ]:
# YOUR CODE IS HERE 



### List the top 3 least common Jobs in the dataset.

In [ ]:
# YOUR CODE IS HERE 



### How many people earned more than avg in 2012?

In [ ]:
# YOUR CODE IS HERE 



### How many people have a title of Manager in their jobs?

In [ ]:
# USE APPLY FUNCTION

# YOUR CODE IS HERE 



### Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe.

In [ ]:
# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/ZgFCbPm/assignment1e.png)

### Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df.

In [ ]:
# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/s2CYS7H/assignment1f.png)

### Print out the names of the employees who earn more than min but less than avg.

In [ ]:
# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/mtNB2TX/assignment1g.png)

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

________